version: 2

jobs:
  build:
    working_directory: ~/python-document-management
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup Python virtual environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run Django tests
          command: |
            . venv/bin/activate
            cp pydocman/pydocman/local_settings.py.dist pydocman/pydocman/local_settings.py
            cd pydocman
            python manage.py test
      - deploy:
          name: Deploy to AWS Lambda
          command: |  
            . venv/bin/activate
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region eu-west-1
            aws configure set default.output json
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                cd pydocman
                zappa update live
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                cd pydocman
                zappa update demo
            fi
