# Generated by Django 2.0.1 on 2018-01-04 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('s3_bucket', models.CharField(max_length=50)),
                ('s3_bucket_key', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('version_major', models.IntegerField()),
                ('version_minor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LenderDocument',
            fields=[
                ('lender_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('lender_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('active_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='lender_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.LenderDocument'),
        ),
    ]
