# Generated by Django 2.0.1 on 2018-01-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180108_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenderdocument',
            name='lender_id',
        ),
        migrations.AddField(
            model_name='lenderdocument',
            name='lender',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='api.Lender'),
            preserve_default=False,
        ),
    ]
