# Generated by Django 2.0.1 on 2018-01-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180108_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('read', 'Read documents'), ('draft', 'Draft documents'), ('publish', 'Publish documents'))},
        ),
    ]
