# Generated by Django 2.0.1 on 2018-01-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180108_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('read_document', 'Read documents'), ('draft_document', 'Draft documents'), ('publish_document', 'Publish documents'))},
        ),
    ]
