# Generated by Django 2.0.1 on 2018-01-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180110_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderdocument',
            name='active_document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document'),
        ),
    ]
