# Generated by Django 2.0.1 on 2018-01-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180117_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lenderdocument',
            options={'permissions': (('create_lender_document', 'Create lender document'),)},
        ),
    ]
